---
title: "p8105_hw5_jg4197"
author: "Jin Ge"
date: "10/31/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message = FALSE,
                      warning = FALSE)

library(tidyverse)
library(rvest)
```

## problem 1 filling in the missing values

```{r}
set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

add_missing <- function(df){
  if(is.numeric(df)){
    df = replace_na(df, mean(df, na.rm = TRUE))
  } else if(is.character(df)){
    df = replace_na(df, "virginica")
  }
}

map_df(iris_with_missing, add_missing)

```

## problem 2 making plot

```{r}
## input files
long_file <- list.files("./hw5_data/data", full.names = TRUE)

## read files
long_data <- map_df(long_file, read_csv)

## tidy the result
data_df <- data_frame(long_file) %>% 
  bind_cols(long_data) %>% 
  mutate(long_file = str_remove(long_file, "./hw5_data/data/"),
         long_file = str_remove(long_file, ".csv")) %>% 
  select(group_id = long_file, everything()) %>% 
  pivot_longer(week_1:week_8,
               names_to = "week",
               values_to = "data") %>% 
  separate(group_id, c("group", "id"), sep = "_", convert = TRUE) %>% 
  mutate(id = factor(id))


## making a plot for longitude data
data_df %>% ggplot(aes(x = week, y = data, group = id)) +
  geom_point(aes(color = id)) + geom_line(aes(color = id), size = .8) +
  facet_wrap(group ~.) + theme_light()



```

## problem 3 conducting simulation

```{r}
sim_model <- function(beta1, beta0 = 2, n = 30){
   sim_data = tibble(
     x = rnorm(n, mean = 0, sd = 1),
     y = beta0 + beta1 * x + rnorm(n, mean = 0, sd = sqrt(50))
   )
   
   fit_line = lm(y~x, data = sim_data)
   
   tidy_test = broom::tidy(fit_line)
   
   tibble(beta1_hat = tidy_test[[2,2]],
          p_value = tidy_test[[2,5]])
}

output <- vector("list", length = 5000)
for(i in 1:5000){
  output[[i]] = sim_model(0)
}
sim_result0 <- bind_rows(output)
sim_result0

## repeat for beta1=1,2,3,4,5,6
rerun_f <- function(beta1){
  rerun(5000, sim_model(beta1))
}

sim_result <- 
  tibble(beta1_true = c(0,1,2,3,4,5,6)) %>% 
  mutate(estimate_df = map(.x = beta1_true, ~rerun_f(beta1 = .x)),
         output_df = map(estimate_df, bind_rows)) %>%
  select(-estimate_df) %>% 
  unnest(output_df)


### making plot for rejected null across beta2
sim_result %>% 
  group_by(beta1_true) %>% 
  summarize(obs_n = n(),
            freq_reject = sum(p_value < 0.05)/obs_n) %>% 
  ggplot(aes(x = beta1_true, y = freq_reject)) + geom_bar(stat = "identity")


### making plot
reject_mean <- sim_result %>% 
  filter(p_value < 0.05) %>% 
  group_by(beta1_true) %>% 
  summarise(average = mean(beta1_hat))

sim_result %>% 
  group_by(beta1_true) %>% 
  summarize(average = mean(beta1_hat)) %>% 
  ggplot(aes(x = beta1_true, y = average)) + geom_bar(stat = "identity") + 
  geom_bar(data = reject_mean, stat = "identity", alpha = .55) + 
  scale_x_continuous(breaks = c(0,1,2,3,4,5,6)) + theme_classic()



```